"""empty message

Revision ID: 7b654c23c1e4
Revises: a4d5dcefb939
Create Date: 2017-11-12 17:40:09.190934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b654c23c1e4'
down_revision = 'a4d5dcefb939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('ag_last_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'ag_last_name')
    # ### end Alembic commands ###
