"""empty message

Revision ID: a4d5dcefb939
Revises: 
Create Date: 2017-11-12 17:39:07.275450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d5dcefb939'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'ag_last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('ag_last_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
